exp_name: "c51-CartPole-v1"  # 自动替换为当前脚本的文件名，需要代码支持来动态赋值
seed: 1
track: false
wandb_project_name: JAXRL-baselines
wandb_entity: sustech-emi-org
capture_video: false
save_model: false
upload_model: false
hf_entity: ""

# Algorithm specific arguments
agent: c51
env_id: "CartPole-v1"
total_timesteps: 500000
learning_rate: 0.00025
num_envs: 1
n_atoms: 101
v_min: -100
v_max: 100
buffer_size: 10000
gamma: 0.99
target_network_frequency: 500
batch_size: 128
start_e: 1
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000
train_frequency: 10
