exp_name: "dqn-Ant"  # Adjust this name based on the actual experiment
seed: 31415
track: false
wandb_project_name: JAXRL-baselines
wandb_entity: None
capture_video: false
save_model: false
upload_model: false
hf_entity: ""

# Algorithm specific arguments
agent: dqn
env_id: ant
total_timesteps: 500000 # 5000000
learning_rate: 0.00025
num_envs: 1
buffer_size: 10000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
batch_size: 128
start_e: 1.0
end_e: 0.05
exploration_fraction: 0.5
learning_starts: 10000 #10000
train_frequency: 10
