# defaults:
#   - override hydra/hydra_logging: none
#   - override hydra/job_logging: none

hydra:
  # hydra_logging:
  #   disable_existing_loggers: true
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  verbose: false
